project:
  type: website
  output-dir: docs

website:
  title: "Michael Eirikson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Projects"
        menu:
        - project1.qmd
        - project2.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



